### ISSUE TITLE
Write the file "COPYING"

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#1]
We should write the license of this project.

I think we will use some hard-license like GPL, it means we cannot use weak license like Apache's or MIT.

So I suggest you, what about use AGPL(https://en.wikipedia.org/wiki/Affero_General_Public_License)?

If we use it, all software connected with our project become AGPL license. It's very strong limitation.

I want to get your feedback. What do you think about license of it?

Best,
Jaewon Choi.

**Comment by maxtortime** [comment]
Currently, Flask is a BSD license. Flask-security is a MIT license. But I don´t know about each license´s relation of top and bottom. So, I think your suggestion is best. I know AGPL is higher than other license.

**Comment by maxtortime** [comment]
I will make LICENSE text file to root directory of our project soon.
