### ISSUE TITLE
deprecation

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#10]
현재 SetupBox 코드 전체를,

deprecated

폴더를 새로 만들어서 그 폴더 안에 다 넣었으면 좋겠네요.

그 이후에 다시 directory design을 합시다. (e.g. src, doc 등등)

의견 주세요.

**Comment by maxtortime** [comment]
네 제 생각엔 폴더 보단 그 브랜치를 만들어서 현재 master브랜치를 넣어놓고 다음에 master브랜치에 앞으로 설계하는 내용을 넣는게 나을 것 같습니다.

**Comment by maxtortime** [comment]
작업 완료해서 이슈 닫겠습니다.
