### ISSUE TITLE
Branch name convention problem

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#11]
branching convention에 대한 얘길 하면 좋을 것 같네요.

먼저 메인 branch인 master, dev는 논외로 하고, topic base branching을 할 때, 오늘 조언을 받은 것처럼 directory based naming이 저는 효율적일 것 같아요.

또한, issue number를 branch이름으로 쓰는 것도 도움이 될 것 같네요.

예를 들면,

실험 : experiments/(이하)
운영 : operations/(이하) --> Readme update 와 같은 branches는 operations/ directory로 관리할 수 있겠죠.

한번 제가 pull request 날려 볼테니, 평가해 주세요.

**Comment by maxtortime** [comment]
제 생각에는 어떻게 하는지 잘 모를 때는 Gif flow를 잘 쓰면 무척 도움이 될 것 같습니다.  http://danielkummer.github.io/git-flow-cheatsheet/  @Jungmo 도 해당 내용 공부해보시고 모르는 게 있으면 알려주세요. Pull request 는 바로 살펴보겠습니다.

오늘 설계 회의 할 때 같이 하면 좋을 것 같군요.

**Comment by maxtortime** [comment]
이 이슈도 정해진 것 같으므로 닫습니다.
https://github.com/maxtortime/SetupBox/wiki/Contribution-guide 에 게시했습니다.
