### ISSUE TITLE
How to use 'Travis CI'?

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#14]
I'm impressed by 'JANDY' project. So, Firstly I adjusted 'Travis CI' to 'SetupBox' but it doesn't working properly. How to work 'Travis CI' properly?

**Comment by jafffy** [comment]
https://travis-ci.org/

이 사이트에 들어가서 tutorial을 읽는 걸 추천합니다.
기본적으로 push가 일어나면 CI를 돌리고, pull request 시 해당 push의 CI 결과를 띄워줌으로써 그 결과를 갖고 토의를 해서 pull request를 개선할 수 있는 것이지요.

jandy의 경우 저는 적용하고 싶은데, jandy를 적용하면 성능 테스트 결과를 pull request 시 평가하여 badge 형태로 달아주는 걸로 알고 있습니다. (e.g. -80ms)

나중에 jandy 개발자 분과 얘기해보죠.

**Comment by maxtortime** [comment]
조금 살펴보니 용도를 깨달았습니다. 
https://github.com/maxtortime/SetupBox/pull/17 에 travis 를 적용했습니다. 살펴보시고 댓글 달아주세요.
잔디 개발자분과는 나중에 얘기해보는게 좋겠네요.
그러면 닫습니다.
