### ISSUE TITLE
Make a contribution guide

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#15]
우리 운영 계획을 세우는 것을 준하여 contribution guide를 만들어 봅시다.

내일 함께 해요.

**Comment by maxtortime** [comment]
https://github.com/maxtortime/SetupBox/wiki/Contribution-guide
https://github.com/maxtortime/SetupBox/wiki/Work-proceeding
차후에 아래에 있는 내용을 위문서에 다시 정리해야 할 필요가 있을 것 같습니다.
이슈 닫습니다
