### ISSUE TITLE
npm을 가이드로 삼아서 운영을 해나가면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#16]
https://github.com/npm/npm

GNU나 Apache는 GitHub가 생기기전부터 존속해왔던 데라 Github 사용법에 대한 참고가 되기는 힘들고
npm이 정말 GitHub를 잘 써먹는 것 같습니다.
커밋 로그 적는 것 부터 시작해서 문서화 및 프로젝트 운영을 npm을 참고해서 하면 많은 도움이 될 것 같습니다.

**Comment by jafffy** [comment]
good idea!

**Comment by maxtortime** [comment]
네 동의하시면 앞으로 npm 들어가서 자주 보시고 npm 링크는 위키 메인에 달아놨습니다.
이슈 닫습니다.
