### ISSUE TITLE
어떻게 터미널에서 바로 SetupBox를 설치하게 할지?

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#2]
현재 생각해 놓은 건 웹서버 부분은 차라리 pypi에 등록해서 설치하게 하면 빠른 설치가 가능 할 것 같은데 client 부분은 어떻게 배포를 해야 할지 공부가 필요할 것 같습니다. 현재 상황에서 먼저 설치 되야 할 라이브러리나 기타 등등이 필요할 것 같은데 어떻게 해야 할 지 지금은 감이 안 오네요.

다양한 의견 부탁드립니다.

**Comment by Jungmo** [comment]
일단 지금 만들어져있는 클라이언트 쪽에서 필요한 패키지는 git, httpie 밖에 없음. (정말 기본적인거 빼고)
근데 svn기반으로 바뀌면 달라질지도?? 리눅스면 데비안계열 / 레드햇계열 나눠서 패키지를 만들어서 배포를 한다던지..
[unixlinux_chapter15.pdf](https://github.com/maxtortime/SetupBox/files/94308/unixlinux_chapter15.pdf)
이게 도움이 될지는 모르겠는데 리눅스기반 패키징 & 배포 라는 제목의 책인데 이런식으로..
pypi에 대해서는 내가 잘 몰라서 어떻게 말을 못하겠네

**Comment by jafffy** [comment]
클라이언트 배포에 대해서는 생각해야 할 다양한 것들이 있음. 장기적으로는 Windows, Mac OS X에서도 클라이언트 패키지가 있어야 하고, 안드로이드, iOS에서도 작동이 되어야 함(3월 내의 목표는 아니지만)
단순히 배포를 편하게 하는 것 뿐 아니라 스크립트 하나 쫙 돌리면 테스팅 다 돌리고 플랫폼 별 빌드가 나와야 하는 것까지 고려하면 이 배포의 문제는 현재 결정해야 하는 우선순위는 아닌 것으로 사려됨.
그 이전에 내가 생각하는 우리의 우선순위는 
1. 웹에서 우리가 생각한 모든 기획이 순조롭게 흘러가도록 하기.
2. 리눅스 클라이언트 아래에서 순조롭도록 할러가게 하기.

이 두가지를 끝내야 그때부터 배포 얘기를 할 수 있을 듯. 우리가 아직 인증이라던지 리소스 관리라던지 이런 것들을 어떻게 할지를 확실히 끝낸 것이 아니기 때문에.
