### ISSUE TITLE
test: CUnit 사용해 보시고 우리 프로젝트에 적용할 수 있는지 평가해주세요.

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#21]
@Jungmo 형, 
http://cunit.sourceforge.net/index.html

아래 링크 보고 cunit 설치하고 돌려 보시고, 우리 프로젝트에 적용 가능한지 평가해 주세요.

**Comment by Jungmo** [comment]
OK. 25일 내로 해보겠음.

**Comment by Jungmo** [comment]
작은 기능부터 새로 만들어서 테스트 해봤습니다.
함수에 대한 리턴값으로 테스트하는 것 같아서 쉽게 두개의 수 중에 minimum을 찾는 함수로 테스트 했습니다.
동작은 당연히 잘 합니다. 많이 어렵지도 않네요.

**Comment by jafffy** [comment]
@Jungmo 감사합니다.

아마 테스트 케이스를 만드는 것과 같은 노가다나 testing 설계가 어려울 것으로 예상됩니다.

닫겠습니다.
