### ISSUE TITLE
doc: AUTHORS 추가

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#22]
https://github.com/maxtortime/SetupBox/pull/23

**Comment by jafffy** [comment]
1. 정모형 email ajm100@ajou.ac.kr 로 바꿔야 함.
2. email 쓰는 convention은 Name email@address 를 쓰는 게 좋을 것 같음

ex.
Jaewon Choi <jainersoer@gmail.com>

**Comment by maxtortime** [comment]
1. 완료
2. 처음에 마크다운 적용되서 이상하게 나온 듯, 파일 보면 제대로 되 있음.
