### ISSUE TITLE
현재 브랜치 명명 방식의 문제점

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#24]
현재 브랜치 명명 방식을 <브랜치명>/<이슈번호> 로 하고 있는데
이렇게 하면 약간 문제가 생기는게 예를 들어 기존에 deprecated 브랜치가 로컬에 있다고 하고 우리가 연결시키려는 이슈번호가 23번이라고 하면,

``` sh
$ git branch deprecated/22
fatal: cannot lock ref 'refs/heads/deprecated/22': 'refs/heads/deprecated' exists; cannot create 'refs/heads/deprecated/22'
```

위와 같은 오류가 발생하는 것을 볼 수 있었다. 이유는 우리가 브랜치를 만들 때마다 위의 오류 메시지에서 볼 수 있듯이 브랜치명으로 된 디렉토리를 ref/heads 에 만들게 된다. 그 후 우리가 다시 그 브랜치의 하부 디렉토리를 만들려고 하면 저렇게 오류가 나는 것이다. 일단 위의 문제를 해결해주는 명령어나 방법이 있을 것으로 예상이 되지만, 위 문제를 가장 무식하게 해결할 수 있는 법은 그냥 

``` sh
$ rm -rf .git/ref/deprecated/
```

라고 하면 더 이상 오류가 나지 않을 것이다. 하지만 별로 좋은 해결방식은 아니므로 [git 책](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#Basic-Merging)에 나온 것처럼 iss53 같은 명명방식을 제안해본다. 혹은 다른 방식도 환영.

**Comment by maxtortime** [comment]
Also plz. read this article: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by jafffy** [comment]
약간의 문제가 아니네. test branch랑 dev branch라는 branch name을 못쓰게 되는거니까.

dev19

이런 식의 네임은 어때?

그리고 올려준 링크에서 네가 어떤 부분을 보고 추천하는 건지도 적어주면 좋을 듯.

**Comment by maxtortime** [comment]
1. 첫 번째 git 책에서는 iss53 처럼 하는 게 마음에 들었음
2. 두 번째 링크는 develop-xx 이런식의 명명 방식도 현재 우리 상황이면 괜찮은것같아서 올려봄

**Comment by jafffy** [comment]
난 develop-xx 명명이 더 낫다고 생각함.

@Jungmo 형은 어떻게 생각해요?

**Comment by maxtortime** [comment]
나도 2안이 낫다고 생각함

**Comment by Jungmo** [comment]
나도 2안

**Comment by maxtortime** [comment]
https://github.com/maxtortime/SetupBox/wiki/Contribution-guide

2안으로 결정하고 위키에 올려놨습니다. 혹시 저기가 아닌 것 같으면 다른 곳에 적어주세요.
현재 있는 브랜치는 일단 머지되면 없애도록 합시다.
이슈 닫습니다,
