### ISSUE TITLE
bmp_diff: How to do? -> ImageMagick

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#25]
I found beautiful program: [ImageMagick](http://www.imagemagick.org/script/index.php) . Also, That program is also [open source](https://github.com/ImageMagick/ImageMagick)! and It also has good [C API](http://www.imagemagick.org/script/magick-wand.php) too. I will analyze ASAP.

**Comment by jafffy** [comment]
네, 이 라이브러리를 적용해 주세요.

닫겠습니다.
