### ISSUE TITLE
doc: 위키 tips 페이지, CUnit 설치 guide 추가

### ISSUE THREAD

**Issue by Jungmo** [maxtortime/SetupBox#28]
Wiki에 tips를 모아두는 페이지 만듦.
Mac 에 CUnit 설치하는 방법에 대해서 추가

**Comment by Jungmo** [comment]
tips에 CUnit 설치관련 작성했습니다. 수정이 필요하다면 말해주세요.

**Comment by jafffy** [comment]
좋습니다.

닫겠습니다.
