### ISSUE TITLE
dev: jsmn(JSON C library)를 dependency로 추가해야 함

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#29]
init 시에 기존의 세팅을 불러올 수 있어야 하는데, 그를 위해서 json 라이브러리를 붙이려고 합니다.

https://github.com/zserge/jsmn

**Comment by Jungmo** [comment]
기존의 세팅이라면 어떤건가요?

**Comment by jafffy** [comment]
@Jungmo 예컨데 현재는 이 프로그램이 처음 실행되는 것인지, 그렇지 않은지 등이 포함됩니다.
나중에는 로그인 정보, 캐시 정보 등등이 포함될 예정이구요.

**Comment by maxtortime** [comment]
그냥 C로 바이너리 설정 파일 만들고 읽으면 안 되나요? 잘 몰라서 여쭤봅니다.

**Comment by jafffy** [comment]
@maxtortime 바이너리 설정 파일을 만들고 읽을 때의 이점을 아직 잘 모르겠는데, json을 기본으로 저장하면 일단 텍스트를 수정하는 방식으로 설정을 바꿀 수 있고, 나중에는 serialize/deserialize를 json으로 만든 flexible한 protocol을 기본으로 할 수 있겠죠.

**Comment by maxtortime** [comment]
https://github.com/maxtortime/SetupBox/wiki/Work-proceeding#211
