### ISSUE TITLE
issue와 pull request를 동시에 만들 이유가 있는지?

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#37]
저희가 이슈 기반 개발을 하기로 한 건 무척 좋은 생각이라고 생각합니다.
그러나 현재 방식 상 issue를 만들고 PR을 다시 만들어야 하는데 생각해보면 issue와 PR은 그 작동방식이 매우 유사하고 하는 일도 비슷한 것 같습니다. 물론 이슈가 있어서 그거에 대한 커밋을 해서 PR을 하는 거라면 맞겠지만 **PR을 하기 위해서 이슈를 만들고 시작하는 건 비효율적인 것 같습니다.**

많은 의견 바랍니다.

**Comment by jafffy** [comment]
이슈랑 PR 연동하는게 있음.
그리고 이슈는 원래 말그대로 이슈에 대한 토론을 하는 거고 풀리퀘는 해당 풀리퀘에 대한 토론을 하는 것이기 때문에 coverage가 다름.

**Comment by maxtortime** [comment]
그럼 한 이슈에 계속 PR이 붙는 형태로 구성을 해야 하는 거군.. 알겠습니다.
