### ISSUE TITLE
Using clib for managing package.

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#38]
I found [clib](https://github.com/clibs/clib) which Package manager for the C. I think it is useful for managing package. I'll use this for adjusting 'jsmn'

**Comment by jafffy** [comment]
이게 왜 우리 프로젝트에 유용한거임?

**Comment by maxtortime** [comment]
왠지 앞으로 패키지를 많이 추가할 것 같은 느낌이 들었음. 그래서 이런 일로 고통받지 않으려고 쓰려고 한건데 굳이 잘 할 수 있다면 안 써도 될듯 ㅇㅇ

**Comment by jafffy** [comment]
패키지를 추가한다는게 어떤 의미임 이 맥락에서?

**Comment by maxtortime** [comment]
여기서는 예를 들어 jsmn 을 추가한다 치면 pip install jsmn 이렇게 하면 알아서 깔리는 모델을 생각하고 이걸 올린거임 나는 ㅋㅋ

**Comment by jafffy** [comment]
난 아직 왜 이게 우리 프로젝트에서 필요한지 파악을 못해서 만약에 정말 essential 하다고 하면 정확히 이게 뭐고 왜 필요한지에 대한 reasoning이 있어야 할 것 같아. dependency가 늘어나는게 필수적이거나 확실한 장점이 있는 상황이 아닌 이상에야 더 좋을게 없을 것 같아 보이거든.

**Comment by maxtortime** [comment]
ㅇㅇ 사실 꼭 필요하다는 건 아니였고 그냥 괜찮다 싶어서 의견을 들어보기 위해 올림 나도 잘 몰라서.. ㅋㅋ

**Comment by jafffy** [comment]
내 생각엔 우리 프로젝트에는 필요 없을 듯 함.
