### ISSUE TITLE
About branching 

### ISSUE THREAD

**Issue by maxtortime** [maxtortime/SetupBox#45]
현재 dev-xx 같이 이슈별로 숫자를 명명해놓고 토픽 브랜치를 push 후에 작업을 진행하고 있습니다.
다음 그 이슈가 해결되면 바로 master로 merge하고 있는데요. 이 방식의 문제점은 모든 기여자가 코드에 버그가 없다고 확신할 수 있어야 하는데 그러지 못하면 master 브랜치에는 버그가 있는 코드가 머지되겠죠.
master 브랜치는 정말로 release 가능한 상태로 유지되야 하는데 지금 상태는 조금 위험한 것 같습니다.

그리고 계속 토픽 브랜치가 많아지다 보니 개발 상태가 누적되지 못하고 분산되있는 것 같습니다.

그래서 현재 develop 브랜치를 올려놨습니다. 아마 토픽 브랜치를 develop에 먼저 머지해주시고 그다음 PR을 날리는 게 좋을 것 같은데 많은 의견 바랍니다.

**Comment by Jungmo** [comment]
좋은 생각입니다

**Comment by maxtortime** [comment]
지금 약간 dev-숫자 이형식으로 가다보니 처음에는 괜찮았던 것 같은데 지금 보니 이슈 숫자하고 해당 이슈에 해당하는 내용이 바로바로 매칭이 안 되는 것 같은데 차라리 숫자대신 간단하게 해당 이슈에서 해결해야 하는 내용을 넣는게 좋지 않을까요?

일단 제 생각은 지금 dev-python 아니면 dev-prototype 이런식이나 아니면
git-flow에서 하는 것처럼 feature/python, feature/prototype 처럼 하는게 좋을 것 같은데
의견 바랍니다!

**Comment by jafffy** [comment]
내 생각엔 오히려 요약해서 내용을 넣는 동안 왜곡이 일어날 가능성이 더 크다고 생각함. 이슈 넘버를 매기는게 더 나은 것 같아.

**Comment by maxtortime** [comment]
그러면 일단 지금처럼 하고 자기가 연건 나중에 확실히 지우는게 좋겠음
