### ISSUE TITLE
C coding convention

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#5]
어떤 code convention을 따를지를 생각해봅시다.

먼저 저는 NetBSD의 Coding convention을 던지고 갑니다.

https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html

참고로 google에서는 Cpp convention만 주고 C convention은 emacs editor configuration만 던져주더군요...ㅠㅠ

**Comment by maxtortime** [comment]
https://github.com/maxtortime/SetupBox/pull/17 에 의견 남겨주세요!
아 그리고 Python 은 [구글](https://google.github.io/styleguide/pyguide.html)이 잘 해놨더군요. 보기는 좀 힘들지만 ..
나중에 위키 [북마크](https://github.com/maxtortime/SetupBox/wiki/Bookmarks) 에 추가해주세요!

**Comment by jafffy** [comment]
@maxtortime 우리 파이썬 쓸건가요?

**Comment by maxtortime** [comment]
나중에 쓸 수 있지 않나 싶어서 .. 오늘 얘기해보죠

**Comment by jafffy** [comment]
@maxtortime 그리고 #17은 author와 라이선스에 대한거라서 coding convention 얘기를 같이 하는게 옳지 않다고 생각합니다.

**Comment by maxtortime** [comment]
NetBSD 쓰기로 오늘 결정했으므로 닫습니다.
https://github.com/maxtortime/SetupBox/wiki/Work-proceeding 참고하세요.
