### ISSUE TITLE
Wiki에 2016.1.22 회의 내용 올리기

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#6]
주요 안건
- 현재 service로서의 우리 서비스를 core module을 제공하는 라이브러리 형태로 전환하자.
- plugin base 디자인을 해서 modularity를 올리자.
- Demo integrated server를 만들어서 사용자가 쉽게 우리의 storage cloud 용 API를 사용할 수 있도록 하자.

혹시 더 안건들이 생각나는 내용들이 있으면 댓글도 달아주세요.

**Comment by maxtortime** [comment]
올려주신 내용 위키에 편집해서 올렸습니다. Github 위키도 Markdown으로 동작하므로 자세한 건 구글에 Github Markdown만 쳐도 잘 알아볼 수 있습니다. 해당 이슈는 닫고 앞으로 Wiki나 Slack을 이용하도록 하죠.
