### ISSUE TITLE
Github 언어 문제 - 한국어 vs 영어

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#7]
지금 제 의견은 일단 한국어로 가고(적어도 3월까진), 그 후에 Documentation 대대적인 개편을 통해 영어로 바꾸는게 효율적이라고 봅니다.

단, 주석의 경우 나중에 바꾸는 것의 비용이 너무 비싸므로 주석은 무조건 영어로 달면 좋을 것 같네요. 게다가 특정 에디터는 한글 지원을 안해서...ㅠㅠ

의견 주세요.

**Comment by maxtortime** [comment]
1. 어차피 결승전 전까지 외국에서 기여자들이 올 확률은 적으므로 생산성 측면에서도 한국어로 하는 게 옳다고 봅니다.
2. 주석은 영어로 하자에 동의합니다. 그런데 한글 주석이 안 되는 거면 혹시 인코딩 설정이 잘 안 되는 건가요?

**Comment by jafffy** [comment]
폰트가 안됨요...ㅠㅠ 그리고 OS에 한글팩 안깔면 한국어 제대로 안나오는 경우도 많구요.

**Comment by maxtortime** [comment]
저는 맥 한글 깔고 나니 맑은 고딕보다 훨씬 이뻐서 그런 고충을 모르고 있었군요. 주석은 영어로 달도록 하겠습니다. 그런 내용은 따로 파일로 만들어서 프로젝트에 올려야 할까요?

**Comment by jafffy** [comment]
나중에 contribution guide를 만들면 그 곳에 적어야겠죠.

**Comment by maxtortime** [comment]
네 그러면 이 논의 내용을 위키에 넣어주실 수 있나요? 그러면 이 부분은 완료 된 것 같네요.
