### ISSUE TITLE
Label 종류 추가

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#8]
Label 종류를 추가해주세요.

저는
- suggestion
- discussion
- operation(운영 문제를 다루는 방식)

정도의 label은 들어가야 한다고 생각하는데, 혹시 이것도 의견 있으시면 계속 주세요.

**Comment by maxtortime** [comment]
네.. 라벨 추가는 한 번도 안 해봐서 어차피 라벨 종류가 많아져도 큰 무리는 없지 않나요? 필요한 것 같으면 잘 추가해 주시면 될 것 같습니다.

**Comment by jafffy** [comment]
아핫. 저는 추가를 제가 할 수 있는지 몰랐네요. 제가 하겠습니다.
