### ISSUE TITLE
master branch merge 권한 문제

### ISSUE THREAD

**Issue by jafffy** [maxtortime/SetupBox#9]
오늘 d2에서 배웠던 것처럼 최소한 세 종류의 branches는 필요한 것 같은데,
- master : end-user가 가져다 쓸 수 있는 형태, 즉 test 완료.
- dev : code review 이후 구현은 완료 되었지만 test는 되지 않은 상태.
- topic-wise : 아직 dev로 가지 못한, 적어도 pull request 이후 refine을 하고 있는 중인 상태와 그 이하의 상태들.

이때 master branch에 merge할 수 있는 권한을 한명이 가지면 좋을 것 같습니다. 그래야 문제를 풀어야 하는 의무라던지 꼬임이 적어질 것이라고 기대할 수 있을 것 같네요.

저는 @maxtortime 이 했으면 좋겠네요.

의견 주세요.

**Comment by maxtortime** [comment]
물론 저희는 3명 이라서 굳이 Merge하는 역할을 따로 둘 필요는 없어보이긴 하지만, 세 명 다 git 명령어에 숙련된 상황이 아니므로 위의 제안도 괜찮은 것 같습니다. 그리고 제가 찾아본 Git 활용 Model 중에도 특정 한 명이 Merge하는 역할을 맡는 경우도 있었고요. 일단 GitHub에 특정 브랜치를 보호할 수 있는 기능이 있습니다. 일단 master 브랜치를 보호해두고 그러면 topic 브랜치에 다른 contributor들이 커밋을 push 하면 제가 깔끔하게 로그 정리등을 해서 커밋하는 게 맞는 것 같습니다.

**Comment by jafffy** [comment]
그러면 그렇게 알겠습니다.
